name: Feature Request
description: Suggest a new feature for the Ultimate Autonomous Agent
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - Core Agent Functionality
        - Security Enhancement
        - Tool Integration
        - Learning/AI Improvement
        - Performance Optimization
        - Documentation
        - Developer Experience
        - Enterprise Feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or need...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: What other approaches have you thought about?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Needed for important use case
        - Critical - Blocking important functionality

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a developer, I want to...
        2. As an enterprise user, I need to...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Feature works as described
        - [ ] Tests are included
        - [ ] Documentation is updated

  - type: input
    id: deadline
    attributes:
      label: Timeline
      description: Do you have a specific timeline or deadline?
      placeholder: ex. Needed by Q2 2024

  - type: checkboxes
    id: complexity
    attributes:
      label: Implementation Complexity (estimate)
      options:
        - label: Simple - Can be implemented in a few hours
        - label: Medium - Requires a few days of work
        - label: Complex - Requires significant design and development
        - label: Major - Requires architectural changes

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      options:
        - label: This feature may require breaking changes
        - label: This feature should be backward compatible

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.

  - type: checkboxes
    id: volunteer
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
        - label: I can provide testing and feedback during development